### PR TITLE
Add a method to scale TransformableNode object in ScaleController class, and add onSingleTap method into the Node.OnTapListener to support the single tap upon a node.

### PR DESCRIPTION
**Pull request by KonsanAlide**
1. Add a method to scale the TransformableNode object in the ScaleController, because i found that the setlocalScale() can not scale the TransformableNode object, the ScaleController object had controlled the scale  function of the TransformableNode and updating the scale value continuously in the method  onUpdated(). 
2. Add onSingleTap() method into the Node.OnTapListener, to do something when a single tap on a Node, 
for example :  put a child node to the click position. The Node.OnTapListener.onTap is also triggered when the Node is dragged, so, i think it is useless.

### CODE REVIEW

**Comment by KonsanAlide** [comment]
I found a question, when i tried to scale a TransformableNode in my program, but is failed, i was surprised!
After some time, i found the reason, the ScaleController had controlled the scale function of the TransformableNode,
it update the scale value continuously in the method onUpdated(), and ignore the scale vector in the Node object,
so, the TransformableNode cannot be scaled using the setlocalScale() function. Now, i add the setScaleRatioAndScale method to scale the TransformableNode in the program, instead of scaling it with my fingers only.
         In my app, i want to get the click position of the model node , i found the OnTapListener.onTap method, but the drag operation on the node also invoke it,  wow, this is a sad story!  No way, I can only add a new method.

**Comment by ThomasGorisse** [comment]
For your case of scalable by the user and programaticly at the same time, a good way to go is:
- WorldScale the parent AnchorNode ( = LocalScale since it's parent is the Scene/World)
- Add an intermediate Node, LocalScale it and add your models children to it.

**Comment by KonsanAlide** [comment]
Thanks thomas! 
     My question is:  i need to put some child nodes upon and into the large parent node in my application ,
and i need to  move and scale the child nodes  using the fingers or the method freely, also, the parent node can do it too. 
     WorldScale the parent AnchorNode will scale all nodes.
     Add an intermediate Node, that is really a good way , but if there are too many child nodes, it will need the same number of intermediate nodes.
     I will think about it for a while,  thanks  thomas again!


    The my submitted code, let's not merge, maybe not need it!  ^_^








| |
Charles Yang
|
|
***@***.***
|
签名由网易邮箱大师定制
On 7/1/2021 20:57，Thomas ***@***.***> wrote：

For your case of scalable by the user and programaticly at the same time, a good way to go is:

WorldScale the parent AnchorNode ( = LocalScale since it's parent is the Scene/World)
Add an intermediate Node, LocalScale it and add your models children to it.

**Comment by KonsanAlide** [comment]
Hi, ThomasGorisse:
      I noticed that in ScaleController, the onUpdated() method has been called continuously, repeatedly setting the scaleValue and calling methods to scale the model, which will lead to greater invalid performance cost. I think this is a problem. In most cases, it is not necessary to set the same scaleValue repeatedly, because the fingers do not touch the model any more. The setLocalScale() method doesn't work for this reason. I modified the implementation of the onUpdated() method to avoid repeating the scale model, and loaded the scaleValue vector of the node. If it is found that the scaleValue has been modified, I will load it and convert it to the corresponding currentScaleRatio.
       However, I'm not sure whether it will lead to other new problems. I've never understood why the onUpdated() method is called continuously, even if no gesture is generated. 
       Here are some things I haven't considered. So, before that, I don't really want to change it like this. 
       It will requires you to do more checking, thanks for your work!

**Comment by ThomasGorisse** [comment]
Hi,

Thanks for your commit.

That's interesting but can you make a quick test adding a lot of entities to the Scene and viewing the difference with and without your cache in the performance monitor?

Sometimes bringing complexity in the code with very little results is not a so good idea.

**Comment by RGregat** [comment]
Is the intention of the onSingleTap Listener to replace this possible workaround?

```java

...
transformableNode.setOnTouchListener(this);
...

@Override
public boolean onTouch(HitTestResult hitTestResult, MotionEvent motionEvent) {
    int action = motionEvent.getActionMasked();
    switch (action) {
        case MotionEvent.ACTION_UP:
            // finger up
            return true;
        case MotionEvent.ACTION_DOWN:
            // Node tap
            return true;
        case MotionEvent.ACTION_MOVE:
            // Node drag
            return true;
    }
    return false;
}
```

**Comment by KonsanAlide** [comment]
@RGregat
       No,  it isn't.
       The purpose of adding this  OnTapListener.onSingleTap() method is to get an single tap event simply. 
       I found the OnTapListener.onTap() , but it will be called when any finger click on a node, it also can't be called by dragging and scaling gesture events.
	   
       Handling the onTouch() event of a node also can't accurately capture a single tap operation. Of course, if you add the GestureDetector to process these motion events in the  onTouch() method,  you can do it .  But if you do that , your program structure will be a bit messy, and there will be a lot of GestureDetector objects,  that may lead to other problems.

**Comment by KonsanAlide** [comment]
@ThomasGorisse :
     I'm  very sorry,  i had made some test , i place 30 models anchor on the plane,  I have tested the two versions of code for many times to observe their CPU and memory usage.
     But  it is almost impossible to compare, because the difference is very small, and due to the mobile phone moves, the observation result has a big error, and these dirty data can not be used to judge the performance comparison of the two versions. I may need to think about how to compare the two versions more accurately！
     I have also considered the complexity problem caused by the addition of new code, but from my evaluation, It should have little impact, because only a few floating-point comparisons have been added, which is far less than the amount of computation required to execute the setLocalScale method.  
      Thanks!

**Pull request closed without merging**
