### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by RGregat**
Updated Filament to version 1.12.8
I have some issues with the material **ar_environment_material_depth**. 
If I don't find a solution in a reasonable amount of time, I use a lower version of Filament.

### CODE REVIEW

**Comment by RGregat** [comment]
The issue with the Depth-Material starts with Filament version 1.12.1

**Comment by ThomasGorisse** [comment]
@RGregat Can you describe the issue?

**Comment by RGregat** [comment]
I found the original issue on the Filament Repository, where the material was posted the first time https://github.com/google/filament/issues/3100

I asked there, if something importand has changed since then.

**Comment by RGregat** [comment]
Since version 1.12.1 and no one noticed it since then? :) I mean is our usecase with overwriting gl_FragDepth that rare?

**Comment by RGregat** [comment]
Ok @ThomasGorisse and @grassydragon with the help of @romainguy and @pixelflinger I was able to fix the last issue with our Depth-Material.

**Pull request merged**
